/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ph.mmhsvictoria.vconf;
import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.shape.Circle;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader loader = new FXMLLoader();
        String cwd = System.getProperty("user.dir");   // This locates where the JVM was invoked.
        // System.out.println("Invoked from " + cwd);
        String path_to_resource = cwd + "/src/main/resources/vconv.fxml";
        loader.setLocation(new URL("file://" + path_to_resource));
    }

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
